# Generated by Django 5.0.3 on 2024-03-15 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('auteur', models.CharField(max_length=100)),
                ('date_publication', models.DateField()),
                ('genre', models.CharField(choices=[('Roman', 'Roman'), ('Nouvelle', 'Nouvelle'), ('Conte', 'Conte'), ('Science-fiction', 'Science-fiction'), ('Fantaisie', 'Fantaisie'), ('Mystère', 'Mystère'), ('Policier', 'Policier'), ('Horreur', 'Horreur'), ('Biographie', 'Biographie'), ('Autobiographie', 'Autobiographie'), ('Essai', 'Essai'), ('Livre de référence', 'Livre de référence'), ('Livre de voyage', 'Livre de voyage'), ("Livre d'histoire", "Livre d'histoire"), ('Livre de sciences', 'Livre de sciences'), ('Poésie', 'Poésie'), ('Science', 'Science'), ('Religion et spiritualité', 'Religion et spiritualité'), ('Arts et divertissement', 'Arts et divertissement'), ('Santé et bien-être', 'Santé et bien-être'), ('Éducation et apprentissage', 'Éducation et apprentissage'), ('Economie', 'Economie'), ('Politique et société', 'Politique et société')], max_length=50)),
                ('date_ajout', models.DateField(auto_now_add=True)),
                ('format', models.CharField(choices=[('Poche', 'Poche'), ('Normal', 'Normal')], max_length=10)),
                ('pret', models.BooleanField(default=False)),
                ('date_pret', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
